#!/bin/bash
# Project Tofu - Rust + wgpu Build Script

set -e

echo "🦀 Project Tofu - Rust + wgpu Build Script"
echo "=========================================="

# Check if Rust is installed
if ! command -v cargo &> /dev/null; then
    echo "❌ Rust is not installed!"
    echo "Install Rust: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
    exit 1
fi

echo "✅ Rust found: $(rustc --version)"

# Build for desktop
echo ""
echo "Building for desktop (native)..."
cargo build --release

echo ""
echo "✅ Build complete!"
echo ""
echo "╔══════════════════════════════════════════════════╗"
echo "║      🧊 Project Tofu - Living UI 🧊            ║"
echo "╚══════════════════════════════════════════════════╝"
echo ""
echo "✨ Pure AI-Driven Interface"
echo "   No presets. No hardcoded shapes."
echo "   Everything generated by AI in real-time."
echo ""
echo "🚀 Usage:"
echo "   cargo run --release -- \"your natural language prompt\""
echo ""
echo "💡 Examples:"
echo "   cargo run --release -- \"show me a DNA helix\""
echo "   cargo run --release -- \"create a spiral galaxy\""
echo "   cargo run --release -- \"visualize quantum particles\""
echo "   cargo run --release -- \"show me chaos becoming order\""
echo ""
echo "📖 Setup: See docs/GEMINI_SETUP.md"
echo "📚 Docs:  See docs/ folder"
echo ""
echo "⌨️  Controls: ESC to quit"
echo ""
